# Week 7 Assignment

_MkKinney 6.1_

This week has been all about getting information off the internet both in structured data formats (CSV, JSON, etc) as well as HTML.  For these exercises, we're going to use two practical examples of fetching data from web pages to show how to use Pandas and BeautifulSoup to extract structured information from the web.

---
---

### 33.1 Parsing a list in HTML

Go to the Banner Health Price Transparency Page: https://www.bannerhealth.com/patients/billing/pricing-resources/hospital-price-transparency

Notice that there is a list of hospitals and the city they are in.  We want to parse the underlying HTML to create a list of all the hospitals along with which city they're in.

```json
[
    ["Banner - University Medical Center Phoenix", "Arizona"],
    ["Banner - University Medical Center South ", "Arizona"],
    ...
]
```

To examine the underlying HTML code, you can use Chrome, right-click, and choose **Inspect**.

For reference, the documentation for BeautifulSoup is here: https://www.crummy.com/software/BeautifulSoup/bs4/doc/

In [1]:
from bs4 import BeautifulSoup
import requests
headers = { "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36" }

response = requests.get('https://www.bannerhealth.com/patients/billing/pricing-resources/hospital-price-transparency', headers=headers)
soup = BeautifulSoup(response.text, 'html.parser')

In [2]:
div = soup.find_all('div', {"class":"col-md-8"})[0]
for hospital_list in div.find_all('ul'):
    state = hospital_list.previous_sibling.previous_sibling.string
    for hospital in hospital_list.find_all('li'):
        print(state, hospital.text)

Arizona Banner - University Medical Center Phoenix
Arizona Banner - University Medical Center South
Arizona Banner - University Medical Center Tucson
Arizona Banner Baywood Medical Center
Arizona Banner Behavioral Health Hospital
Arizona Banner Boswell Medical Center
Arizona Banner Casa Grande Medical Center
Arizona Banner Del E. Webb Medical Center
Arizona Banner Desert Medical Center/Cardon Children's Medical Center
Arizona Banner Estrella Medical Center
Arizona Banner Gateway Medical Center/Banner MD Anderson Cancer Center
Arizona Banner Goldfield Medical Center
Arizona Banner Heart Hospital
Arizona Banner Ironwood Medical Center
Arizona Banner Ocotillo Medical Center
Arizona Banner Payson Medical Center
Arizona Banner Thunderbird Medical Center
Arizona Page Hospital
California Banner Lassen Medical Center
Colorado Banner Fort Collins Medical Center
Colorado McKee Medical Center
Colorado North Colorado Medical Center
Colorado Sterling Regional Medical Center
Colorado East Morgan County Hospital
Nebraska Ogallala Community Hospital
Nevada Banner Churchill Community Hospital
Wyoming Banner Wyoming Medical Center
Wyoming Community Hospital
Wyoming Washakie Medical Center
Wyoming Platte County Memorial Hospital
State-Specific Regulations Arizona
State-Specific Regulations California
State-Specific Regulations Colorado
State-Specific Regulations Nebraska
State-Specific Regulations Nevada
State-Specific Regulations Wyoming

---

### 33.2 Using Pandas to Read Tables


Pandas documentation for loading data https://pandas.pydata.org/pandas-docs/version/0.23.4/api.html#input-output

Pandas documentation for describing the shape of data https://pandas.pydata.org/pandas-docs/version/0.23.4/generated/pandas.DataFrame.shape.html

In [3]:
import pandas as pd

In [4]:
tables = pd.read_html('https://en.wikipedia.org/wiki/Diagnosis-related_group')
len(tables)

5

In [5]:
for index,table in enumerate(tables):
    print("**************TABLE {}".format(index))
    print(table)

**************TABLE 0
    0                                                  1
0 NaN  This article has multiple issues. Please help ...
1 NaN  This article needs to be updated. Please updat...
2 NaN  This article needs additional citations for ve...
**************TABLE 1
    0                                                  1
0 NaN  This article needs to be updated. Please updat...
**************TABLE 2
    0                                                  1
0 NaN  This article needs additional citations for ve...
**************TABLE 3
   Hypothetical patient at Generic Hospital in San Francisco, CA, DRG 482, HIP & FEMUR PROCEDURES EXCEPT MAJOR JOINT W/O CC/MCC (2001)[15]:8  \
0                                         Description
1                              Average length of stay
2                      Large urban labor-related rate
3                       Large urban non-labor-related
4                                          Wage index
5   Standard Federal Rate: labor * wage index + no...
6                     DRG relative weight (RW) factor
7    Weighted payment: Standard Federal Rate * DRG RW
8                Disproportionate Share Payment (DSH)
9                    Indirect medical education (IME)
10                   Total cost outlier reimbursement
11  Total operating payment: Weighted payment * (1...

   Hypothetical patient at Generic Hospital in San Francisco, CA, DRG 482, HIP & FEMUR PROCEDURES EXCEPT MAJOR JOINT W/O CC/MCC (2001)[15]:8.1
0                                               Value
1                                             3.8[16]
2                                           $2,809.18
3                                           $1,141.85
4                                              1.4193
5                                           $5,128.92
6                                              1.8128
7                                           $9,297.71
8                                              0.1413
9                                              0.0744
10                                                 $0
11                                         $11,303.23
**************TABLE 4
     Name  Version       Start date  \
0  MS-DRG       25  October 1, 2007
1  MS-DRG       26  October 1, 2008
2  MS-DRG       27  October 1, 2009
3  MS-DRG       31  October 1, 2013
4  MS-DRG       32  October 1, 2014
5  MS-DRG       33  October 1, 2015
6  MS-DRG       34  October 1, 2016
7  MS-DRG       35  October 1, 2017

                                               Notes
0  Group numbers resequenced, so that for instanc...
1  One main change: implementation of Hospital Ac...
2  Changes involved are mainly related to Influen...
3                                                NaN
4                                                NaN
5            Convert from ICD-9-CM to ICD-10-CM.[17]
6  Address ICD-10 replication issues introduced i...
7  MS-DRGs 984 through 986 deleted and reassigned...

In [6]:
drgs = tables[4]
drgs

,Name,Version,Start date,Notes
0,MS-DRG,25,"October 1, 2007","Group numbers resequenced, so that for instanc..."
1,MS-DRG,26,"October 1, 2008",One main change: implementation of Hospital Ac...
2,MS-DRG,27,"October 1, 2009",Changes involved are mainly related to Influen...
3,MS-DRG,31,"October 1, 2013",NaN
4,MS-DRG,32,"October 1, 2014",NaN
5,MS-DRG,33,"October 1, 2015",Convert from ICD-9-CM to ICD-10-CM.[17]
6,MS-DRG,34,"October 1, 2016",Address ICD-10 replication issues introduced i...
7,MS-DRG,35,"October 1, 2017",MS-DRGs 984 through 986 deleted and reassigned...

---

### 33.3 Find Something of Your Own

Do some web searches and find an HTML page with some data that is interesting to something you're studying.  You can extract and parse that information using either BeautifulSoup or Pandas.  If you're using Pandas, then do something interesting to format and structure your data.  If you're using BeautifulSoup, you'll just need to do the work of parsing the data out of HTML -- that's hard enough!

You don't need to build this as a function.  Just use notebook cells as I've done above.  You will be graded based on _style_.  Use variable names that make sense for your problem / solution. Cleanup anything you don't need before you submit your work.

In [7]:
import pandas as pd

In [8]:
#Tables pulls the html table from the National Highway Transportation Safety Administration for the rankings of all states for pedestrian crash fatalities
#I do a lot of safety analysis at work and my master's thesis is focused on pedestrian safety 


tables = pd.read_html('https://www-fars.nhtsa.dot.gov/States/StatesPedestrians.aspx')
len(tables)

12

In [9]:
#This line of code prints all tables on the web page to make it easy to see which table is the one I actually want
#For the sake of not printing 50 pages of tables, I left off the print(table) at the end of the for loop

for index,table in enumerate(tables):
    print("****TABLE {}****".format(index))

****TABLE 0****
****TABLE 1****
****TABLE 2****
****TABLE 3****
****TABLE 4****
****TABLE 5****
****TABLE 6****
****TABLE 7****
****TABLE 8****
****TABLE 9****
****TABLE 10****
****TABLE 11****

In [10]:
#This line of code prints the table I think is the one I want to check if it is correct

print(tables[0])

                                                 Rank                 State  \
0                                                   1            New Mexico
1                                                   2             Louisiana
2                                                   3               Florida
3                                                   4               Arizona
4                                                   5        South Carolina
5                                                   6                Hawaii
6                                                   7           Mississippi
7                                                   8                Nevada
8                                                   9               Georgia
9                                                  10              Delaware
10                                                 11            California
11                                                 12               Alabama
12                                                 13        North Carolina
13                                                 14                 Texas
14                                                 15              Maryland
15                                                 16              Arkansas
16                                                 17             Tennessee
17                                                 18            New Jersey
18                                                 19                Oregon
19                                                 20                Alaska
20                                                 21               Indiana
21                                                 22           Connecticut
22                                                 23              Kentucky
23                                                 24  District of Columbia
24                                                 25              Colorado
25                                                 26              Missouri
26                                                 27          Pennsylvania
27                                                 28              Oklahoma
28                                                 29              Michigan
29                                                 30               Montana
30                                                 31              Virginia
31                                                 32            Washington
32                                                 33              New York
33                                                 34              Illinois
34                                                 35              Nebraska
35                                                 36         West Virginia
36                                                 37                  Utah
37                                                 38          South Dakota
38                                                 39         Massachusetts
39                                                 40                  Ohio
40                                                 41               Wyoming
41                                                 42                Kansas
42                                                 43                 Idaho
43                                                 44             Wisconsin
44                                                 45               Vermont
45                                                 46          North Dakota
46                                                 47             Minnesota
47                                                 48                  Iowa
48                                                 49         New Hampshire
49                                                 50          Rhode Island
50                                                 51                 Maine
51                                                NaN                   USA
52                                                NaN                   NaN
53  SummaryTrendsCrashesVehiclesPeopleStates  Cras...                   NaN

    Pedestrians Killed  Population (Thousands)  \
0                 83.0                  2095.0
1                164.0                  4660.0
2                704.0                 21299.0
3                237.0                  7172.0
4                165.0                  5084.0
5                 42.0                  1420.0
6                 88.0                  2987.0
7                 79.0                  3034.0
8                261.0                 10519.0
9                 23.0                   967.0
10               893.0                 39557.0
11               107.0                  4888.0
12               225.0                 10384.0
13               612.0                 28702.0
14               128.0                  6043.0
15                62.0                  3014.0
16               136.0                  6770.0
17               173.0                  8909.0
18                80.0                  4191.0
19                14.0                   737.0
20               114.0                  6692.0
21                60.0                  3573.0
22                73.0                  4468.0
23                11.0                   702.0
24                89.0                  5696.0
25                95.0                  6126.0
26               197.0                 12807.0
27                60.0                  3943.0
28               142.0                  9996.0
29                15.0                  1062.0
30               118.0                  8518.0
31               102.0                  7536.0
32               262.0                 19542.0
33               165.0                 12741.0
34                24.0                  1929.0
35                22.0                  1806.0
36                36.0                  3161.0
37                10.0                   882.0
38                78.0                  6902.0
39               127.0                 11689.0
40                 6.0                   578.0
41                29.0                  2912.0
42                17.0                  1754.0
43                56.0                  5814.0
44                 6.0                   626.0
45                 6.0                   760.0
46                42.0                  5611.0
47                22.0                  3156.0
48                 9.0                  1356.0
49                 7.0                  1057.0
50                 7.0                  1338.0
51              6283.0                327167.0
52                 NaN                     NaN
53                 NaN                     NaN

    Pedestrian Fatality Rate per 100,000 Population  Unnamed: 5  Unnamed: 6  \
0                                              3.96         NaN         NaN
1                                              3.52         NaN         NaN
2                                              3.31         NaN         NaN
3                                              3.30         NaN         NaN
4                                              3.25         NaN         NaN
5                                              2.96         NaN         NaN
6                                              2.95         NaN         NaN
7                                              2.60         NaN         NaN
8                                              2.48         NaN         NaN
9                                              2.38         NaN         NaN
10                                             2.26         NaN         NaN
11                                             2.19         NaN         NaN
12                                             2.17         NaN         NaN
13                                             2.13         NaN         NaN
14                                             2.12         NaN         NaN
15                                             2.06         NaN         NaN
16                                             2.01         NaN         NaN
17                                             1.94         NaN         NaN
18                                             1.91         NaN         NaN
19                                             1.90         NaN         NaN
20                                             1.70         NaN         NaN
21                                             1.68         NaN         NaN
22                                             1.63         NaN         NaN
23                                             1.57         NaN         NaN
24                                             1.56         NaN         NaN
25                                             1.55         NaN         NaN
26                                             1.54         NaN         NaN
27                                             1.52         NaN         NaN
28                                             1.42         NaN         NaN
29                                             1.41         NaN         NaN
30                                             1.39         NaN         NaN
31                                             1.35         NaN         NaN
32                                             1.34         NaN         NaN
33                                             1.30         NaN         NaN
34                                             1.24         NaN         NaN
35                                             1.22         NaN         NaN
36                                             1.14         NaN         NaN
37                                             1.13         NaN         NaN
38                                             1.13         NaN         NaN
39                                             1.09         NaN         NaN
40                                             1.04         NaN         NaN
41                                             1.00         NaN         NaN
42                                             0.97         NaN         NaN
43                                             0.96         NaN         NaN
44                                             0.96         NaN         NaN
45                                             0.79         NaN         NaN
46                                             0.75         NaN         NaN
47                                             0.70         NaN         NaN
48                                             0.66         NaN         NaN
49                                             0.66         NaN         NaN
50                                             0.52         NaN         NaN
51                                             1.92         NaN         NaN
52                                              NaN         NaN         NaN
53                                              NaN         NaN         NaN

    Unnamed: 7  Unnamed: 8  Unnamed: 9  Unnamed: 10
0          NaN         NaN         NaN          NaN
1          NaN         NaN         NaN          NaN
2          NaN         NaN         NaN          NaN
3          NaN         NaN         NaN          NaN
4          NaN         NaN         NaN          NaN
5          NaN         NaN         NaN          NaN
6          NaN         NaN         NaN          NaN
7          NaN         NaN         NaN          NaN
8          NaN         NaN         NaN          NaN
9          NaN         NaN         NaN          NaN
10         NaN         NaN         NaN          NaN
11         NaN         NaN         NaN          NaN
12         NaN         NaN         NaN          NaN
13         NaN         NaN         NaN          NaN
14         NaN         NaN         NaN          NaN
15         NaN         NaN         NaN          NaN
16         NaN         NaN         NaN          NaN
17         NaN         NaN         NaN          NaN
18         NaN         NaN         NaN          NaN
19         NaN         NaN         NaN          NaN
20         NaN         NaN         NaN          NaN
21         NaN         NaN         NaN          NaN
22         NaN         NaN         NaN          NaN
23         NaN         NaN         NaN          NaN
24         NaN         NaN         NaN          NaN
25         NaN         NaN         NaN          NaN
26         NaN         NaN         NaN          NaN
27         NaN         NaN         NaN          NaN
28         NaN         NaN         NaN          NaN
29         NaN         NaN         NaN          NaN
30         NaN         NaN         NaN          NaN
31         NaN         NaN         NaN          NaN
32         NaN         NaN         NaN          NaN
33         NaN         NaN         NaN          NaN
34         NaN         NaN         NaN          NaN
35         NaN         NaN         NaN          NaN
36         NaN         NaN         NaN          NaN
37         NaN         NaN         NaN          NaN
38         NaN         NaN         NaN          NaN
39         NaN         NaN         NaN          NaN
40         NaN         NaN         NaN          NaN
41         NaN         NaN         NaN          NaN
42         NaN         NaN         NaN          NaN
43         NaN         NaN         NaN          NaN
44         NaN         NaN         NaN          NaN
45         NaN         NaN         NaN          NaN
46         NaN         NaN         NaN          NaN
47         NaN         NaN         NaN          NaN
48         NaN         NaN         NaN          NaN
49         NaN         NaN         NaN          NaN
50         NaN         NaN         NaN          NaN
51         NaN         NaN         NaN          NaN
52         NaN         NaN         NaN          NaN
53         NaN         NaN         NaN          NaN

In [11]:
#This line of code assigns the correct table to a variable to easily pull up the table

ped_stats = tables[6]

In [12]:
ped_stats

,Rank,State,Pedestrians Killed,Population (Thousands),"Pedestrian Fatality Rate per 100,000 Population",Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10
0,1.0,New Mexico,83.0,2095.0,3.96,NaN,NaN,NaN,NaN,NaN,NaN
1,2.0,Louisiana,164.0,4660.0,3.52,NaN,NaN,NaN,NaN,NaN,NaN
2,3.0,Florida,704.0,21299.0,3.31,NaN,NaN,NaN,NaN,NaN,NaN
3,4.0,Arizona,237.0,7172.0,3.30,NaN,NaN,NaN,NaN,NaN,NaN
4,5.0,South Carolina,165.0,5084.0,3.25,NaN,NaN,NaN,NaN,NaN,NaN
5,6.0,Hawaii,42.0,1420.0,2.96,NaN,NaN,NaN,NaN,NaN,NaN
6,7.0,Mississippi,88.0,2987.0,2.95,NaN,NaN,NaN,NaN,NaN,NaN
7,8.0,Nevada,79.0,3034.0,2.60,NaN,NaN,NaN,NaN,NaN,NaN
8,9.0,Georgia,261.0,10519.0,2.48,NaN,NaN,NaN,NaN,NaN,NaN
9,10.0,Delaware,23.0,967.0,2.38,NaN,NaN,NaN,NaN,NaN,NaN
10,11.0,California,893.0,39557.0,2.26,NaN,NaN,NaN,NaN,NaN,NaN
11,12.0,Alabama,107.0,4888.0,2.19,NaN,NaN,NaN,NaN,NaN,NaN
12,13.0,North Carolina,225.0,10384.0,2.17,NaN,NaN,NaN,NaN,NaN,NaN
13,14.0,Texas,612.0,28702.0,2.13,NaN,NaN,NaN,NaN,NaN,NaN
14,15.0,Maryland,128.0,6043.0,2.12,NaN,NaN,NaN,NaN,NaN,NaN
15,16.0,Arkansas,62.0,3014.0,2.06,NaN,NaN,NaN,NaN,NaN,NaN
16,17.0,Tennessee,136.0,6770.0,2.01,NaN,NaN,NaN,NaN,NaN,NaN
17,18.0,New Jersey,173.0,8909.0,1.94,NaN,NaN,NaN,NaN,NaN,NaN
18,19.0,Oregon,80.0,4191.0,1.91,NaN,NaN,NaN,NaN,NaN,NaN
19,20.0,Alaska,14.0,737.0,1.90,NaN,NaN,NaN,NaN,NaN,NaN
20,21.0,Indiana,114.0,6692.0,1.70,NaN,NaN,NaN,NaN,NaN,NaN
21,22.0,Connecticut,60.0,3573.0,1.68,NaN,NaN,NaN,NaN,NaN,NaN
22,23.0,Kentucky,73.0,4468.0,1.63,NaN,NaN,NaN,NaN,NaN,NaN
23,24.0,District of Columbia,11.0,702.0,1.57,NaN,NaN,NaN,NaN,NaN,NaN
24,25.0,Colorado,89.0,5696.0,1.56,NaN,NaN,NaN,NaN,NaN,NaN
25,26.0,Missouri,95.0,6126.0,1.55,NaN,NaN,NaN,NaN,NaN,NaN
26,27.0,Pennsylvania,197.0,12807.0,1.54,NaN,NaN,NaN,NaN,NaN,NaN
27,28.0,Oklahoma,60.0,3943.0,1.52,NaN,NaN,NaN,NaN,NaN,NaN
28,29.0,Michigan,142.0,9996.0,1.42,NaN,NaN,NaN,NaN,NaN,NaN
29,30.0,Montana,15.0,1062.0,1.41,NaN,NaN,NaN,NaN,NaN,NaN
30,31.0,Virginia,118.0,8518.0,1.39,NaN,NaN,NaN,NaN,NaN,NaN
31,32.0,Washington,102.0,7536.0,1.35,NaN,NaN,NaN,NaN,NaN,NaN
32,33.0,New York,262.0,19542.0,1.34,NaN,NaN,NaN,NaN,NaN,NaN
33,34.0,Illinois,165.0,12741.0,1.30,NaN,NaN,NaN,NaN,NaN,NaN
34,35.0,Nebraska,24.0,1929.0,1.24,NaN,NaN,NaN,NaN,NaN,NaN
35,36.0,West Virginia,22.0,1806.0,1.22,NaN,NaN,NaN,NaN,NaN,NaN
36,37.0,Utah,36.0,3161.0,1.14,NaN,NaN,NaN,NaN,NaN,NaN
37,38.0,South Dakota,10.0,882.0,1.13,NaN,NaN,NaN,NaN,NaN,NaN
38,39.0,Massachusetts,78.0,6902.0,1.13,NaN,NaN,NaN,NaN,NaN,NaN
39,40.0,Ohio,127.0,11689.0,1.09,NaN,NaN,NaN,NaN,NaN,NaN
40,41.0,Wyoming,6.0,578.0,1.04,NaN,NaN,NaN,NaN,NaN,NaN
41,42.0,Kansas,29.0,2912.0,1.00,NaN,NaN,NaN,NaN,NaN,NaN
42,43.0,Idaho,17.0,1754.0,0.97,NaN,NaN,NaN,NaN,NaN,NaN
43,44.0,Wisconsin,56.0,5814.0,0.96,NaN,NaN,NaN,NaN,NaN,NaN
44,45.0,Vermont,6.0,626.0,0.96,NaN,NaN,NaN,NaN,NaN,NaN
45,46.0,North Dakota,6.0,760.0,0.79,NaN,NaN,NaN,NaN,NaN,NaN
46,47.0,Minnesota,42.0,5611.0,0.75,NaN,NaN,NaN,NaN,NaN,NaN
47,48.0,Iowa,22.0,3156.0,0.70,NaN,NaN,NaN,NaN,NaN,NaN
48,49.0,New Hampshire,9.0,1356.0,0.66,NaN,NaN,NaN,NaN,NaN,NaN
49,50.0,Rhode Island,7.0,1057.0,0.66,NaN,NaN,NaN,NaN,NaN,NaN
50,51.0,Maine,7.0,1338.0,0.52,NaN,NaN,NaN,NaN,NaN,NaN
51,NaN,USA,6283.0,327167.0,1.92,NaN,NaN,NaN,NaN,NaN,NaN
52,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53,NaN,2018 Ranking of STATE Pedestrian Fatality Rate...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
#This line of code removes the last 4 rows to trim the table down to just the 50 states

ped_stats_states = ped_stats.drop([51, 52, 53, 54])

In [14]:
#This line of code deletes the end 6 columns in the table which do not display useful information

ped_stats_formatted = ped_stats_states.drop(columns = ['Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10'])

In [15]:
ped_stats_formatted

,Rank,State,Pedestrians Killed,Population (Thousands),"Pedestrian Fatality Rate per 100,000 Population"
0,1.0,New Mexico,83.0,2095.0,3.96
1,2.0,Louisiana,164.0,4660.0,3.52
2,3.0,Florida,704.0,21299.0,3.31
3,4.0,Arizona,237.0,7172.0,3.30
4,5.0,South Carolina,165.0,5084.0,3.25
5,6.0,Hawaii,42.0,1420.0,2.96
6,7.0,Mississippi,88.0,2987.0,2.95
7,8.0,Nevada,79.0,3034.0,2.60
8,9.0,Georgia,261.0,10519.0,2.48
9,10.0,Delaware,23.0,967.0,2.38
10,11.0,California,893.0,39557.0,2.26
11,12.0,Alabama,107.0,4888.0,2.19
12,13.0,North Carolina,225.0,10384.0,2.17
13,14.0,Texas,612.0,28702.0,2.13
14,15.0,Maryland,128.0,6043.0,2.12
15,16.0,Arkansas,62.0,3014.0,2.06
16,17.0,Tennessee,136.0,6770.0,2.01
17,18.0,New Jersey,173.0,8909.0,1.94
18,19.0,Oregon,80.0,4191.0,1.91
19,20.0,Alaska,14.0,737.0,1.90
20,21.0,Indiana,114.0,6692.0,1.70
21,22.0,Connecticut,60.0,3573.0,1.68
22,23.0,Kentucky,73.0,4468.0,1.63
23,24.0,District of Columbia,11.0,702.0,1.57
24,25.0,Colorado,89.0,5696.0,1.56
25,26.0,Missouri,95.0,6126.0,1.55
26,27.0,Pennsylvania,197.0,12807.0,1.54
27,28.0,Oklahoma,60.0,3943.0,1.52
28,29.0,Michigan,142.0,9996.0,1.42
29,30.0,Montana,15.0,1062.0,1.41
30,31.0,Virginia,118.0,8518.0,1.39
31,32.0,Washington,102.0,7536.0,1.35
32,33.0,New York,262.0,19542.0,1.34
33,34.0,Illinois,165.0,12741.0,1.30
34,35.0,Nebraska,24.0,1929.0,1.24
35,36.0,West Virginia,22.0,1806.0,1.22
36,37.0,Utah,36.0,3161.0,1.14
37,38.0,South Dakota,10.0,882.0,1.13
38,39.0,Massachusetts,78.0,6902.0,1.13
39,40.0,Ohio,127.0,11689.0,1.09
40,41.0,Wyoming,6.0,578.0,1.04
41,42.0,Kansas,29.0,2912.0,1.00
42,43.0,Idaho,17.0,1754.0,0.97
43,44.0,Wisconsin,56.0,5814.0,0.96
44,45.0,Vermont,6.0,626.0,0.96
45,46.0,North Dakota,6.0,760.0,0.79
46,47.0,Minnesota,42.0,5611.0,0.75
47,48.0,Iowa,22.0,3156.0,0.70
48,49.0,New Hampshire,9.0,1356.0,0.66
49,50.0,Rhode Island,7.0,1057.0,0.66
50,51.0,Maine,7.0,1338.0,0.52

In [16]:
#This line of code calculates the average fatalities accross all 50 states

average_fatalities = ped_stats_formatted['Pedestrians Killed'].sum() / 50

In [17]:
average_fatalities

125.66

In [18]:
#This line of code calculates the average rate of fatality per 100,000 population accross all 50 states

average_rate = ped_stats_formatted['Pedestrian Fatality Rate per 100,000 Population'].sum() / 50

In [19]:
average_rate

1.7664

---

## Submitting Your Work

In order to submit your work, you'll need to use the `git` command line program to **add** your homework file (this file) to your local repository, **commit** your changes to your local repository, and then **push** those changes up to github.com.  From there, I'll be able to **pull** the changes down and do my grading.  I'll provide some feedback, **commit** and **push** my comments back to you.  Next week, I'll show you how to **pull** down my comments.

To run through everything one last time and submit your work:
1. Use the `Kernel` -> `Restart Kernel and Run All Cells` menu option to run everything from top to bottom and stop here.
2. Save this note with Ctrl-S (or Cmd-S)
2. Skip down to the last command cell (the one starting with `%%bash`) and run that cell.

If anything fails along the way with this submission part of the process, let me know.  I'll help you troubleshoort.

In [20]:
assert False, "DO NOT REMOVE THIS LINE"

AssertionError: DO NOT REMOVE THIS LINE

---

In [21]:
%%bash
git pull
git add week08_assignment_2.ipynb
git commit -a -m "Submitting the week 8 programming assignment"
git push

Already up to date.
[main 246e56e] Submitting the week 8 programming assignment
 1 file changed, 2246 insertions(+)
 create mode 100644 week08/week08_assignment_2.ipynb

To github.com:nsokolis/hds5210-2021.git
   a9bfe1d..246e56e  main -> main


---

If the message above says something like _Submitting the week 8 programming assignment_ or _Everything is up to date_, then your work was submitted correctly.